# Generated by Django 5.0.2 on 2024-05-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0004_productinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='order',
        ),
    ]
