# Generated by Django 5.0.2 on 2024-05-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0006_alter_productinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Processing'), ('s', 'Shipped'), ('d', 'Delivered'), ('i', 'Issued')], default='p', help_text='Status of the order', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
