# Generated by Django 5.0.2 on 2024-05-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0014_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
