# Generated by Django 5.0.2 on 2024-05-18 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0015_remove_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineshop.client'),
        ),
    ]
