# Generated by Django 5.0.2 on 2024-05-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0016_alter_productinstance_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='onlineshop.productinstance'),
        ),
    ]
