# Generated by Django 5.0.2 on 2024-05-18 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0025_pickuplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineshop.pickuplocation'),
        ),
    ]
