# Generated by Django 5.0.2 on 2024-05-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0031_client_date_of_birth_client_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
