# Generated by Django 5.0.2 on 2024-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0033_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('video', models.FileField(upload_to='company_info/')),
                ('logo', models.ImageField(upload_to='company_info/')),
                ('history', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
    ]
