# Generated by Django 5.0.2 on 2024-05-19 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0036_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
