# Generated by Django 5.0.2 on 2024-09-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0037_article_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='banner1',
            field=models.ImageField(blank=True, null=True, upload_to='company_info/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='banner2',
            field=models.ImageField(blank=True, null=True, upload_to='company_info/'),
        ),
    ]
