# Generated by Django 5.0.2 on 2024-09-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0038_companyinfo_banner1_companyinfo_banner2'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
