# Generated by Django 5.0.2 on 2024-09-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0039_manufacturer_logo_manufacturer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='privacy_policy',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
    ]
