# Generated by Django 5.0.2 on 2024-09-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0040_companyinfo_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='privacy_policy',
            field=models.FileField(blank=True, null=True, upload_to='employee_photos/policies/'),
        ),
    ]
