# Generated by Django 5.0.2 on 2024-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0041_alter_companyinfo_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='company_info/'),
        ),
    ]
